builds:
  - env:
      - CGO_ENABLED=0
      - GOPRIVATE="github.com/spacelift-io"
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags: [-trimpath, -v]
    goos: [windows, linux, darwin]
    goarch: [amd64, arm64]
    binary: "{{ .ProjectName }}"

archives:
  # Our GitHub Action relies on this format and file path, so please don't change it:
  # https://github.com/spacelift-io/setup-spacectl
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

release:
  draft: false
  extra_files:
    - glob: ./key.*

changelog:
  use: github-native

winget:
  - name: "{{ .ProjectName }}"
    publisher: spacelift-io
    license: "MIT"
    homepage: https://github.com/spacelift-io/spacectl
    short_description: "Spacelift client and CLI"
    repository:
      owner: mbialon
      name: winget-pkgs
      branch: "spacectl-{{.Version}}"
      token: "{{ .Env.WINGET_GITHUB_TOKEN }}"
      pull_request:
        enabled: false
